/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f327ea37-d2f5-4183-871e-c8907ab55aac",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GBRUxqRaJ",
    "aws_user_pools_web_client_id": "4a0s57jqn571s7fuhff10ie9ol",
    "oauth": {
        "domain": "rabbithole-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://rabbithole-aws.shop/chat/",
        "redirectSignOut": "https://rabbithole-aws.shop/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "rabbithole-claims95512-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
